### ISSUE TITLE
Spearman score for CIFAR10

### ISSUE THREAD

**Issue by yuntaod** [MadryLab/datamodels-data#4]
Hi,

Thanks for your great work and data! I download the datamodel data of cifar10 with 50pct. Specifcally, `train_masks_50pct.npy`, `train_margins_50pct.npy`,  and datamodel `train_50pct.pt` are ready. Then I use datamodel for prediction with LASSO like:

```
pred_margin = mask @ weight + bias
corr = scipy.stats.spearmanr(pred_margin, train_margin).correlation
mse = np.mean((pred_margin - curr_margin) ** 2) / 2
```

However, the mean Spearman correlation is around 0.91 and the MSE is around 1.9, which is lower than the paper (Spearman 0.993 and MSE 1.4). Is there something I missing or it is not proper to directly predict the marginal like this? (I am not sure the lambda is useful during inference)

Hope you can help me with the problem,

Thank you

**Comment by sung-max** [comment]
Hi Yuntao!

Thanks for the kind words!

I believe this discrepancy is due to us using a different evaluation set
for the Figure in the paper,
where we averaged the outputs for a given mask over ten different models
(i.e., for a given mask,
we train a model ten times, and record the average outputs).
This reduces the variance, which would account for the discrepancy you're
seeing.

Also, make sure you're using a "hold out" set when evaluating correlation
or MSE
(e.g., the masks/outputs used to compute the datamodels is non-overlapping
with those used to evaluate).

Let me know if you have other questions.

**Comment by yuntaod** [comment]
Hi @sung-max ,

Thanks for your reply! So for the provided downloadable margins, has it been averaged? Or the average is only used in evaluation?

I also noticed that when you train the datamodel for x, x is always not included on the subset (mask) you train (equation 13 in paper). Is there some reason to do this? What if the datamodel is trained with the subset that x is in it?

Looking forward to your reply,

Thanks,
Yuntao
